export const productsForMen = [
  {
    id: 1,
    name: "Classic Leather Jacket",
    price: 199.99,
    category: "Apparel",
    brand: "FashionX",
    color: "Black",
    size: "L",
    description: "A stylish and durable leather jacket for men.",
  },
  {
    id: 2,
    name: "Smart Watch",
    price: 149.99,
    category: "Electronics",
    brand: "TechPro",
    color: "Silver",
    description: "A feature-rich smartwatch with a sleek design.",
  },
  {
    id: 3,
    name: "Men's Running Shoes",
    price: 79.99,
    category: "Footwear",
    brand: "Athleto",
    color: "Blue/White",
    size: "10",
    description: "Comfortable running shoes for men with great cushioning.",
  },
  {
    id: 4,
    name: "Slim Fit Jeans",
    price: 59.99,
    category: "Apparel",
    brand: "DenimX",
    color: "Dark Blue",
    size: "32/34",
    description: "Stylish and trendy jeans for men.",
  },
  {
    id: 5,
    name: "Gaming Headset",
    price: 89.99,
    category: "Electronics",
    brand: "GameTech",
    color: "Black/Red",
    description: "High-quality gaming headset with immersive sound.",
  },
  {
    id: 6,
    name: "Cotton Polo Shirt",
    price: 39.99,
    category: "Apparel",
    brand: "FashionX",
    color: "Navy Blue",
    size: "M",
    description: "A classic polo shirt made from soft cotton fabric.",
  },
  {
    id: 7,
    name: "Leather Wallet",
    price: 29.99,
    category: "Accessories",
    brand: "LeatherCraft",
    color: "Brown",
    description: "A stylish and durable leather wallet for men.",
  },
  {
    id: 8,
    name: "Stainless Steel Watch",
    price: 119.99,
    category: "Accessories",
    brand: "TimeMaster",
    color: "Black",
    description: "A sophisticated and water-resistant wristwatch for men.",
  },
  {
    id: 9,
    name: "Sports Sunglasses",
    price: 49.99,
    category: "Accessories",
    brand: "SunSport",
    color: "Black/Red",
    description: "UV protected sunglasses for outdoor sports activities.",
  },
  {
    id: 10,
    name: "Casual Sneakers",
    price: 69.99,
    category: "Footwear",
    brand: "StreetStyle",
    color: "White",
    size: "9",
    description: "Comfortable and stylish sneakers for everyday wear.",
  },
];

export const productsForWomen = {
  products: [
    {
      id: "1",
      name: "Women's Leather Jacket",
      category: "Clothing",
      price: 99.99,
      color: "Black",
      size: ["S", "M", "L"],
      description: "A stylish and trendy leather jacket for women.",
      rating: 4.5,
      image: "https://example.com/images/womens_leather_jacket.jpg",
    },
    {
      id: "2",
      name: "Women's Running Shoes",
      category: "Footwear",
      price: 79.99,
      color: "Pink",
      size: ["6", "7", "8"],
      description: "Comfortable and lightweight running shoes for women.",
      rating: 4.2,
      image: "https://example.com/images/womens_running_shoes.jpg",
    },
    {
      id: "3",
      name: "Women's Denim Jeans",
      category: "Clothing",
      price: 59.99,
      color: "Blue",
      size: ["XS", "S", "M", "L"],
      description: "Classic denim jeans for a stylish look.",
      rating: 4.0,
      image: "https://example.com/images/womens_denim_jeans.jpg",
    },
    {
      id: "4",
      name: "Women's Handbag",
      category: "Accessories",
      price: 49.99,
      color: "Brown",
      size: ["One Size"],
      description: "A trendy handbag with ample space for essentials.",
      rating: 4.8,
      image: "https://example.com/images/womens_handbag.jpg",
    },
    {
      id: "5",
      name: "Women's Floral Dress",
      category: "Clothing",
      price: 69.99,
      color: "Multicolor",
      size: ["S", "M", "L"],
      description: "A beautiful floral dress for special occasions.",
      rating: 4.6,
      image: "https://example.com/images/womens_floral_dress.jpg",
    },
    {
      id: "6",
      name: "Women's Wristwatch",
      category: "Accessories",
      price: 129.99,
      color: "Rose Gold",
      size: ["One Size"],
      description: "An elegant wristwatch with a metal strap.",
      rating: 4.4,
      image: "https://example.com/images/womens_wristwatch.jpg",
    },
    {
      id: "7",
      name: "Women's Workout Leggings",
      category: "Clothing",
      price: 39.99,
      color: "Black",
      size: ["XS", "S", "M", "L"],
      description: "Stretchable and comfortable leggings for workouts.",
      rating: 4.3,
      image: "https://example.com/images/womens_workout_leggings.jpg",
    },
    {
      id: "8",
      name: "Women's Sunglasses",
      category: "Accessories",
      price: 29.99,
      color: "Tortoise",
      size: ["One Size"],
      description: "Stylish sunglasses to protect your eyes from the sun.",
      rating: 4.7,
      image: "https://example.com/images/womens_sunglasses.jpg",
    },
    {
      id: "9",
      name: "Women's Formal Blouse",
      category: "Clothing",
      price: 49.99,
      color: "White",
      size: ["XS", "S", "M", "L"],
      description: "A sophisticated blouse for formal occasions.",
      rating: 4.1,
      image: "https://example.com/images/womens_formal_blouse.jpg",
    },
    {
      id: "10",
      name: "Women's Leather Boots",
      category: "Footwear",
      price: 109.99,
      color: "Brown",
      size: ["6", "7", "8"],
      description: "Stylish and durable leather boots for women.",
      rating: 4.9,
      image: "https://example.com/images/womens_leather_boots.jpg",
    },
  ],
};
